name: Convert Markdown to Wikipedia Markup

on:
  push:
    paths:
      - 'drafts/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Convert drafts to wiki format
        run: |
          for file in drafts/*.md; do
            pandoc "$file" -f markdown -t mediawiki -o "${file%.md}.wiki"
          done
      - name: Commit wiki files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add drafts/*.wiki
          git commit -m "Auto-generate wiki files from markdown" || echo "No changes to commit"
          git push
